### ISSUE TITLE
Remove the audio exercise from week 1 

### ISSUE THREAD

**Issue by maczokni** [maczokni/crimemapping_textbook_bookdown#5]
I still think it's a cool exercise but it caused some unnecessary struggle, so let's replace with something more basic? 

One idea: What about a graph of babynames? It's what we use in the summer school: https://rcatlord.github.io/GSinR/ (look at intro tab - has slides where we talk them through it and then code for them to modify. We do it as a guided live coding, actually students might like that on the first session, so we nudge them in gently?

Other ideas welcome

**Comment by jjmedinaariza** [comment]
Sorted. We use cowsay now. And they like it.
