### ISSUE TITLE
Images for week 2

### ISSUE THREAD

**Issue by jjmedinaariza** [maczokni/crimemapping_textbook_bookdown#7]
Some images are missing. They link to internet resources no longer available for sections that you built. Can you check?

This is one of them: http://neondataskills.org/images/dc-spatial-vector/pnt_line_poly.png

**Comment by jjmedinaariza** [comment]
We should in any case use a more consistent system for storing the images and then invoking them. Some sit in this img folder, some are sitting in the img folder for other of your repos. That may be efficient for storing I guess, but it run the risk of getting us into trouble if you delete any of those old repos?

**Comment by jjmedinaariza** [comment]
For example, this one is also missing:
https://raw.githubusercontent.com/maczokni/MSCD/master/imgs/fn2187.png)

**Comment by maczokni** [comment]
Images for all weeks now all local
